### ISSUE TITLE
Support apollo-link-state

### ISSUE THREAD

**Issue by hollandThomas** [lfades/next-with-apollo#10]
Thanks for this library!

It would be great if support for [apollo-link-state](https://github.com/apollographql/apollo-link-state) could be added.

There is currently [this](https://github.com/apollographql/apollo-link-state/issues/185) issue which produces a `[Network error]: TypeError: Cannot read property 'propertyName' of undefined` for properties with a `@client` directive.

As soon as that's resolved, it would be a nice addition to this helper library.

**Comment by lfades** [comment]
`apollo-link-state` will not be supported by the custom configs because those are not removed in favor of the usage of a custom `ApolloClient` and `apollo-boost`, see: #13
