### ISSUE TITLE
How to make sure a new ApolloClient instance is created for each request?

### ISSUE THREAD

**Issue by carolina-cascade** [lfades/next-with-apollo#100]
I am hunting down a bug in my application, deployed with Netlify. I have two pages: in one users click on a button and create a record in a database using a mutation. On the second page, a list of the time of those clicks can be seen, with another button that can filter by months. 

On this second page, the list is loaded SSR with `getInitialProps`. In the deployed Netlify site, loading the page skips the latest records, as if the page is reading from an old cache. However clicking on the filtering button for the current month (which calls the same query as `getInitialProps`)  does shows them.

Thinking it was the Apollo Cache, I disabled it for all queries, and this did not fix the issue. More reading, and I found the [SSR section on the Apollo docs](https://www.apollographql.com/docs/react/performance/server-side-rendering/#server-initialization): there they are using Express, and creating a new instance for each request. Then I came over [this question about multiple clients](https://github.com/lfades/next-with-apollo/issues/32), where @lfades says 
> otherwise you'll be using the same Apollo instance over the entire server

I wonder if the stale data is a consequence of the same Apollo instance being reused, but I don't know how to make sure a new client is created for every request. This is my configuration:

`graphqlClient.js`
```javascript
const errorLink = onError(({graphQLErrors, networkError}) => {
  if (graphQLErrors) {
    graphQLErrors.map(({message, locations, path}) =>
      console.log(`[GraphQL error]: Message: ${message}, 
                                    Location: ${locations}, 
                                    Path: ${path}`));
  }
  if (networkError) {
    console.log(`[Network error]: ${networkError}`);
  }
});

const serverLink = createHttpLink({
  headers: {
    authorization: authorizationStr
  },
  uri: `${stableEndpointURL}${stableEndpointPath}`
});

export default withApollo(
  ({initialState}) => new ApolloClient({
      cache: new InMemoryCache(),
      link: ApolloLink.from([errorLink, serverLink]),
      ssrMode: typeof window === "undefined"
    })
);
```

Which then I use in `_app.js`:
```javascript
import withData from 'graphqlClient';

class MyApp extends App {
  render() {
    const {Component, pageProps, apollo} = this.props;

    return (
      <ApolloProvider client={apollo}>
        <... other providers>
           <Component {...pageProps} />
        </... other providers>
      </ApolloProvider>
    );
  }
}

export default withData(MyApp);
```

Is this the right way to ensure my clients are not reusing the same ApolloClient instance?

Thank you!

**Comment by lfades** [comment]
`next-with-apollo` receives a function that returns the Apollo Client, it's made that way because the package calls the function again every time a new client is required, and it expects a new client every time.

the issue in your code is that you have dependencies of the Apollo Client outside the function. Do the following instead:

```js

export default withApollo(
  ({initialState}) => {
    const errorLink = onError(({graphQLErrors, networkError}) => {
      if (graphQLErrors) {
        graphQLErrors.map(({message, locations, path}) =>
          console.log(`[GraphQL error]: Message: ${message}, 
                                        Location: ${locations}, 
                                        Path: ${path}`));
      }
      if (networkError) {
        console.log(`[Network error]: ${networkError}`);
      }
    });

    const serverLink = createHttpLink({
      headers: {
        authorization: authorizationStr
      },
      uri: `${stableEndpointURL}${stableEndpointPath}`
    });

    return new ApolloClient({
      cache: new InMemoryCache(),
      link: ApolloLink.from([errorLink, serverLink]),
      ssrMode: typeof window === "undefined"
    })
);
```

**Comment by lfades** [comment]
If the issue persists please let me know and I'll open it, also if you can provide a reproduction that would be way better.

**Comment by carolina-cascade** [comment]
Muchas gracias, @lfades, I changed the code to what you suggested. My issue persists, but after your answer I don't think it's connected with next-with-apollo. It does not happen when running my app locally with `npm run dev` and `netlify dev`. Thank you so much again for your fast response!
