### ISSUE TITLE
getDataFromTree throws errors in 5.0.0

### ISSUE THREAD

**Issue by Sabir001** [lfades/next-with-apollo#104]
In my `withData` file, I have specified `{ getDataFromTree: 'ssr' }`

It worked perfectly in `4.3.0`. But, it throws errors in `5.0.0`.

**Comment by lfades** [comment]
The API changed, you have to provide the `getDataFromTree` function, which is no longer provided by the package, like this:
```tsx
import { getDataFromTree } from '@apollo/react-ssr';

withApollo(() => {}, { getDataFromTree })
```
