### ISSUE TITLE
Support for Apollo Client 3

### ISSUE THREAD

**Issue by jkjustjoshing** [lfades/next-with-apollo#106]
Apollo-client 3 is in the beta phase now, with release planned within the next month or so (most likely - no date has been committed to yet).

The dependencies for next-with-apollo should be updated as needed.

This probably will require a `5.0.0` major version bump since this is a breaking change.

**Comment by chemicalkosek** [comment]
The 5.0.0 version works fine for me with apollo client 3 (release date probably 12th February).

**Comment by jkjustjoshing** [comment]
Oh interesting, I now see there is a `5.0.0` release. But there's no release notes, `CHANGELOG.md`, or anything in `README` indicating it supports Apollo v3. I recommend throwing something into the docs or release notes indicating this!

Thanks!

**Comment by chemicalkosek** [comment]
I'm not even sure if 5.0 is an apollo v3 release. There is a breaking change in terms of not bundling @apollo/react-ssr and maybe something else. I don't know.

**Comment by hoangvvo** [comment]
`next-with-apollo` is independent from Apollo Client version because you are [supplying](https://github.com/lfades/next-with-apollo#how-to-use) it with your Apollo Client. The previous versions has a dependency on @apollo/react-ssr, which only work with v2, but it is not the case anymore.

**Comment by lfades** [comment]
Closing this because this package doesn't depend on Apollo packages as @hoangvvo said, try to be up to date with the beta of Apollo 3 because they had multiple version with `getDataFromTree` not working at all.
