### ISSUE TITLE
Cookie not passed to initial load + apollo queries run twice on load

### ISSUE THREAD

**Issue by gwendall** [lfades/next-with-apollo#109]
I have an app in which i handle auth through a token in cookies. This cookie is then read through an Apollo server middleware to authenticate queries. However, when the page first renders, this cookie is not found and the first Apollo query can't get authenticated. Once the page is loaded, a second query gets fired, and the cookie is successfully read this time, so the query gets authenticated. Is there something else I should consider to get the cookie readable through the server rendering ?

**Comment by lfades** [comment]
Before making a query to GraphQL you have to make sure that the Apollo Client is sending the cookie inside `req.headers.cookie`, in the first request with SSR there's no browser instance so you have to send it manually.

**Comment by gwendall** [comment]
Indeed I figured it out. I ended up having to attach a custom fetch function to my Apollo links, which passes the cookies through headers (which it didn’t do by default, strangely). Thanks !

Gwendall Esnault

**Comment by lfades** [comment]
I'm glad you figured it out 😌 , closing it now.
