### ISSUE TITLE
Use apolloClient from getServerSideProps

### ISSUE THREAD

**Issue by alexvilchis** [lfades/next-with-apollo#115]
Hello, I have been doing server-side fetching with the apollo client successfully by obtaining it from the ctx object provided to `getInitialProps`.

However, if I use the new recommended `getServerSideProps` function (NextJS 9.3), the ctx object is not passed the client instance.

Is this feature coming? Should I make a PR?

**Comment by lfades** [comment]
This is a little trickier than before, the new `getServerSideProps` method is not a static method inside the Page, but a export in the page instead, to add Apollo to it properly would require more steps, additionally to this the method doesn't have access to the `AppTree` component (intentionally) which is used to apply server side rendering with the Apollo Client, making the migration even more difficult.

**Comment by alexvilchis** [comment]
Oh, I see. Hopefully the migration can be considered in the plans for the future. Thank you.
