### ISSUE TITLE
authorization header

### ISSUE THREAD

**Issue by AliNazariii** [lfades/next-with-apollo#116]
Hi
Why I can't use `localStorage` in `withApollo.js`?

I run this code:
```javascript
import withApollo from 'next-with-apollo';`
import ApolloClient, { InMemoryCache } from 'apollo-boost';
import { ApolloProvider } from '@apollo/react-hooks';

export default withApollo(
  ({ initialState }) => {
    return new ApolloClient({
      uri: 'http://localhost:8000/graphql/',
      cache: new InMemoryCache().restore(initialState || {}),
      headers: {
        authorization: localStorage.getItem("token")
      }
    });
  },
  {
    render: ({ Page, props }) => {
      return (
        <ApolloProvider client={props.apollo}>
          <Page {...props} />
        </ApolloProvider>
      );
    }
  }
);
```

and I see this error:
`
ReferenceError: localStorage is not defined
module.exports../lib/withApollo.js.__webpack_exports__.default.next_with_apollo__WEBPACK_IMPORTED_MODULE_1___default.render.Page.Page
./lib/withApollo.js:11
`

Can you help me?

**Comment by chemicalkosek** [comment]
localStorage is only client side so it's undefined server side

**Comment by vedovato** [comment]
Hey, how did you solve this issue? Couldn't get auth headers to work either using localStorage or Cookies.

**Comment by AliNazariii** [comment]
I add this part before using localStorage:
```javascript
let token = null;
if (typeof window !== 'undefined') {
        token = localStorage.getItem('token')
}
```

This is a complete usage:
```javascript
let token = null;
if (typeof window !== 'undefined') {
        token = localStorage.getItem('token')
}
const { data, loading, error } = useQuery(QUERY_POST, {
	context: {
		headers: {
			authorization: "JWT " + token,
		}
	}
})
```

I hope it would help you.

**Comment by vedovato** [comment]
So the solution is to set the header info on every Query instead of only once at ApolloClient constructor? Does this work for SSR?

**Comment by AliNazariii** [comment]
Yes, It works for SSR but I didn't want to use my token in ApolloClient. I think (and I hope) it works in ApolloClient, too.
