### ISSUE TITLE
What's the meaning of `It's better to add Apollo in every page instead if you have pages that don't need Apollo.`?

### ISSUE THREAD

**Issue by bexoss** [lfades/next-with-apollo#120]
First thanks for share this library. 

In the `README` there is a part `It's better to add Apollo in every page instead if you have pages that don't need Apollo` But I cannot understand this well because of my poor english. 

Is it better to use `withApollo` to _app.js once or not?

Thanks...

**Comment by chemicalkosek** [comment]
If you have pages that don't need Apollo (don't need to fetch any data, like documentation etc) then you don't need to add withApollo to those pages. Those pages will be statically generated. If you add withApollo in _app.js you opt out from automatic static generation.
