### ISSUE TITLE
How to reinitialize apollo after login, logout?

### ISSUE THREAD

**Issue by Sqveeze** [lfades/next-with-apollo#122]
`
import React from 'react';
import App from 'next/app';
import withApollo from "next-with-apollo";
import ApolloClient, { InMemoryCache } from "apollo-boost";
import gql from 'graphql-tag';
import { ApolloProvider } from "@apollo/react-hooks";
import Cookie from "js-cookie";
import cookies from 'next-cookies';
import 'semantic-ui-css/semantic.min.css';
import '../styles/style.scss';

const GRAPHQL_URL = process.env.NODE_ENV === 'production' ? '***/graphql' : '***/graphql';

// import withData from '../utils/apollo';

const getCookie = async (ctx) => {
  let res = null;
  if (typeof window === undefined) {
    const { token } = cookies(ctx);
    res = token;
  } else {
    const token = Cookie.get("token");
    res = token;
  }
  return res;
}

class MyApp extends App {
  render() {
    const { Component, pageProps, apollo } = this.props;

    return (
      <ApolloProvider client={apollo}>
        <Component {...pageProps} />
      </ApolloProvider>
    );
  }
}

export default withApollo(({ initialState, ctx }) => {
  let authToken = null;
  if (typeof window === undefined) {
    const { token } = cookies(ctx);
    authToken = token;
  } else {
    const token = Cookie.get("token");
    authToken = token;
  }
  // const token = getCookie(ctx);
  return new ApolloClient({
    uri: GRAPHQL_URL,
    cache: new InMemoryCache().restore(initialState || {}),
    headers: {
      ...(authToken && { Authorization: `Bearer ${authToken}` }),
    },
  });
})(MyApp);
`

My questions is, how to reinitialize after login or logout? And also would be good to know, how to check properly on server if i logged in or not, because i get

`Prop className did not match. Server: "sign-in icon" Client: "user icon"`

error if i check the login status with cookie

**Comment by HaNdTriX** [comment]
fyi: https://www.apollographql.com/docs/react/networking/authentication/#reset-store-on-logout
