### ISSUE TITLE
Next.js SSR Regression when using 5.0.0 instead of 4.3.0

### ISSUE THREAD

**Issue by Vadorequest** [lfades/next-with-apollo#126]
I'm in the process of updating my OSS repository dependencies for https://github.com/UnlyEd/next-right-now, see PR https://github.com/UnlyEd/next-right-now/pull/27.

I've noticed upgrading to `next-with-apollo@5.0.0`, breaks SSR support.

### Summary

- https://nrn-v1-ssr-mst-aptd-gcms-lcz-sty-c1-hajt5ir65.now.sh/ works fine ([commit](https://github.com/UnlyEd/next-right-now/commit/7fd91e467ae0adc70396d9f4335e308540403083))
- **https://nrn-v1-ssr-mst-aptd-gcms-lcz-sty-c1-bj7yrw148.now.sh/ doesn't work ([commit](https://github.com/UnlyEd/next-right-now/commit/8251a67c2b3defe4bc48af8eea76be355e939bca)) -  REGRESSION DUE TO next-with-apollo@5.0.0**
        - Restoring to this commit locally proves that, previous commit works fine with SSR, but doesn't when `next-with-apollo@5.0.0` is being used.

Full detail in the PR description. 

I'm likely gonna rewrite the branch history to remove next-with-apollo@5.0.0 (use 4.3.0) and see how it goes from there. I've thoroughly tested deployments one by one, with small subset of dependencies updates and I'm 100% positive next-with-apollo@5.0.0 breaks it, I've reproduced this behaviour locally.

**Comment by chemicalkosek** [comment]
In 5.0.0 to have SSR you need to pass getDataFromTree. From docs:

```
// import { getDataFromTree } from '@apollo/react-ssr';
// You can also override the configs for withApollo here, so if you want
// this page to have SSR (and to be a lambda) for SEO purposes and remove
// the loading state, uncomment the import at the beginning and this:
//
// export default withApollo(Index, { getDataFromTree });
```

**Comment by Vadorequest** [comment]
Thank you, I'll investigate. 

Note that this behaviour will also be affected by updating to `react-apollo@3.1.4`, because it installs `@apollo/react-ssr` in yarn.lock file. See https://github.com/apollographql/react-apollo/compare/react-apollo@3.1.3...react-apollo@3.1.4

I reproduced the regression locally upgrading either libraries, but on the online demo it's only affected when upgrading next-with-apollo, not when upgrading react-apollo, for some unknown reason...

Anyway, I'll follow your advice and migrate to 5.0.0 and see how it goes.

**Comment by Vadorequest** [comment]
@chemicalkosek Thank you very much for your help, I managed to fix this issue. See https://github.com/UnlyEd/next-right-now/pull/27/commits/5f3ad97d7e815129774c22c6a210daaa858f6b45

**Comment by Vadorequest** [comment]
I suggest to reference this issue for other people who'd migrate from v4 to v5 though.
