### ISSUE TITLE
Version 3 breaking changes

### ISSUE THREAD

**Issue by lfades** [lfades/next-with-apollo#13]
Some changes have been made in the branch [v2.2](https://github.com/lfades/next-with-apollo/tree/v2.2) that got me thinking, do we really need to have custom configs to create an `ApolloClient` ? it would be much simpler to just have support for any `ApolloClient`, specially because I think most people will go for `apollo-boost`, the only downside I see is to implement subscriptions and other stuff that's not yet in `apollo-boost` (related to this [issue](https://github.com/apollographql/apollo-client/issues/3024)) but even for that we can just create our custom ApolloClient and follow Apollo's docs to integrate the different links

Related to #12

**Comment by lfades** [comment]
Here's an example that does the same of the custom config included by this package:

```js
```

**Comment by SpaceK33z** [comment]
> do we really need to have custom configs to create an ApolloClient ?

I'd say no, it barely reduces the code you have to write as a user (as far as I can see). Also not having the custom configs makes this package less likely to break in the future (smaller surface area), and more flexible with possibly exotic Apollo use cases (not sure if there are any, just a theoretical thingy).

**Comment by LawJolla** [comment]
Thanks for all of your hard work!

I couldn't make this config work.
```
TypeError: Cannot read property 'length' of undefined
    at isTerminating (/Users/wheelkinetics/PhpstormProjects/wk_v2/node_modules/apollo-link/lib/bundle.umd.js:53:29)
    at split ...
```

I think the issue is `split` cannot take false for wsLink.  I did get this to work, though ugly

```
  const link = wsLink
    ? split(
        // split based on operation type
        ({ query }) => {
          const definition = getMainDefinition(query)
          return (
            definition.kind === "OperationDefinition" &&
            definition.operation === "subscription"
          )
        },
        wsLink,
        ApolloLink.from([errorLink, contextLink, httpLink])
      )
    : ApolloLink.from([errorLink, contextLink, httpLink])
```

**Comment by williamli** [comment]
@lfades how do I pass headers from _app.js into withApollo?

```
export default withApollo(MyApp);
```

Right now I am getting `TypeError: Cannot read property 'authorization' of undefined` for `authorization: headers.authorization`

**Comment by williamli** [comment]
@lfades I followed your example but `headers` is not getting passed into `withApollo`.

I am getting a `TypeError: Cannot read property 'authorization' of undefined` on `headers.authorization`

**Comment by lfades** [comment]
@williamli Right, `headers` is only defined in SSR, in the client `headers` is `undefined`, I'll update the example again, thank you 💃 .
