### ISSUE TITLE
Allow error handling on the server

### ISSUE THREAD

**Issue by eddeee888** [lfades/next-with-apollo#134]
At the moment, errors are silently caught and ignored on the server when running `getDataFromTree` [here](https://github.com/lfades/next-with-apollo/blob/f5c7b2f39cd06845fa4697053a73cf9281798167/src/withApollo.tsx#L73-L97). This means even if the graphql server sends back an error in query results, the NextJS server does not know this and will always return 200 which is bad for SEO.

It would be nice to be able to pass an error handler to the options to be able to handle this.

For example, this is what's happening in my app:
```ts
// ComponentA.tsx

const ComponentA = () => {
  const { data, error } = useGetUserQuery();

  if( error ){
    // I want to throw an error with code "500" in here to be caught when running on the server
    // On the client, it shows an error page
    return <Error500 />
  }

  if( !data ||  !data.user ) {
    // I want to throw an error with code "404" in here to be caught when running on the server
   // On the client, it shows an error page
    return <Error404 />
  }
  ...
}
```

If `withApollo` uses a function passed in from the options, we can update the context so NextJS returns correct status code:

```ts
const MyAppWithApollo = withApollo(
  ({ initialState, headers }) => createApolloClient({ uri: process.env.GRAPHQL_ENDPOINT, initialState, ssrHeaders: headers }),
  {
    getDataFromTree,
    handleServerError: ( ctx, err ) => {
         ctx.res.statusCode = err.code; // This is an example, may need more checks in prod
    }
  }
)(MyApp);
```

Happy to create a PR if this makes sense :)

**Comment by Emiliano-Bucci** [comment]
That would be great, as now we can't show a 404 page becase we always get a 200 :/

**Comment by honi** [comment]
I would be interested in this as well.

**Comment by markplindsay** [comment]
@eddeee888, I, too, would love a solution for `if(!data || !data.user ) return <Error404 />` that returns a 404 status code when encountered server-side. 

Today, actually, I've got to solve this problem one way or another. :-( I'm weighing my options on duplicating my `useQuery` in a page's `getInitialProps` to set the 404 if `data.user === null` (ugh) or temporarily abandoning `next-with-apollo` for custom code incorporating your idea.

**Comment by rajington** [comment]
submitted #138 that will show a 500 page in SSR or break during SSG, let me know what you think

**Comment by Emiliano-Bucci** [comment]
@rajington Seems cool! One thing: could be maybe useful to pass to the `onError` function, along with the error, the status code?

**Comment by rajington** [comment]
This is happening at the data fetching level, it's impossible to know whether you would want to show a 404 (e.g. a product doesn't exist) or a 500 (e.g. invalid query). You'd have to look at the `error` that is being passed to the function to decide. Or handle it in the `link` if you mean the code from the GraphQL server. This function could only add values that are in scope [here](https://github.com/lfades/next-with-apollo/pull/138/files#diff-34a4f2658f21cf398e2aa210d8ff7c35R83)

**Comment by Emiliano-Bucci** [comment]
@rajington Yes you're right, i misunderstood, sorry! Cool, anyway!

**Comment by eddeee888** [comment]
I think if we passed the NextJS `ctx` [here](https://github.com/lfades/next-with-apollo/pull/138/files#diff-34a4f2658f21cf398e2aa210d8ff7c35R56) back to the handler, we'll be able to change `ctx.res.statusCode` to 404 or 500. This will make NextJS return the same status code

**Comment by rajington** [comment]
just added, will have to think about the test

**Comment by rajington** [comment]
added some tests for 404 and 500, but I'm not sure if that's the best way to do it in next, I would've thought I don't need to explicitly define the body and can rely on next's built-in pages

**Comment by eddeee888** [comment]
> but I'm not sure if the example app is updating the context in the best way
I was also on the fence at first so I looked around and currently, we have these options :
- manually change the `res` as we do here so we return the correct code.
- sending a soft 404 i.e. returning 200 with `noindex` as mentioned here: https://github.com/zeit/next.js/discussions/10960. However, this is generally a bad practice

I prefer the first option though since it's the standard way to handle requests.

Anyways, @rajington thanks for implementing this! 🙏

**Comment by rajington** [comment]
thanks, any idea when we can merge it and re-publish a package? we're currently using this and don't want to use patch-package

**Comment by rajington** [comment]
@eddeee888 whenever the PR gets merged, i think it will automatically close this ticket, just wanted to confirm it solved your use case

**Comment by eddeee888** [comment]
It does, @rajington. I tested the implementation locally and it worked for my use case!

**Comment by Emiliano-Bucci** [comment]
Any news on when the pr will be merged?
