### ISSUE TITLE
Support Next.js v11

### ISSUE THREAD

**Issue by exneval** [lfades/next-with-apollo#164]
Currently the package will throw error :
`TypeError: head_1.default.rewind is not a function`

As per v11, the usage of `Head.rewind` can safely be removed.

Can you look into this @lfades ?
Thanks in advanced.

**Comment by GodwinEbikwo** [comment]
Getting the same issue after upgrading to Next.js 11
TypeError: head_1.default.rewind is not a function

**Comment by antonybudianto** [comment]
I've forked my own to `next-with-apollo2@11` for now. Really waiting for the official update on this 🙏🏻
