### ISSUE TITLE
Type error with typescript using example

### ISSUE THREAD

**Issue by dbtlr** [lfades/next-with-apollo#19]
I'm following the example to set up next-with-apollo and am trying to do so using typescript instead of regular JavaScript. However, I'm getting the follow error when I do so:

```
[ts]
Argument of type 'typeof MyApp' is not assignable to parameter of type 'typeof App'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'TProps & AppComponentProps' is not assignable to type 'Props & AppComponentProps'.
      Type 'TProps & AppComponentProps' is not assignable to type 'Props'.
        Property 'apollo' is missing in type 'AppComponentProps'.
class MyApp
```

Here is my `_app.tsx`

```
import App, { Container } from 'next/app';
import ApolloClient from 'apollo-boost';
import { ApolloProvider } from 'react-apollo';
import withApollo from '../lib/withApollo';

interface Props {
  apollo: ApolloClient<any>;
}

class MyApp extends App<Props> {
  render() {
    const { Component, pageProps, apollo } = this.props;

    return (
      <Container>
        <ApolloProvider client={apollo}>
          <Component {...pageProps} />
        </ApolloProvider>
      </Container>
    );
  }
}

export default withApollo(MyApp);
```

The `withApollo.ts` didn't change from the example in the README.

Did I miss some simple here? I assumed given that this was written in TypeScript that it should work pretty simply.

Thanks!!

**Comment by lfades** [comment]
When I switched the package to `_app.js` the types for `next/app` were not yet added, see [here](https://github.com/lfades/next-with-apollo/blob/master/src/app.d.ts), but now I should use the new types, do you want to do a PR or can you wait until friday ?

**Comment by dbtlr** [comment]
I'll likely wait, I'm not fully sure how to add the type in and lack the time this week to learn. I'll look forward to seeing the PR so that I can know how to do this in the future :)

Thanks so much!

**Comment by lfades** [comment]
Hi @dbtlr ! sorry for the delay, here's the PR: #21 , do you want to do a review ?

**Comment by hisea** [comment]
Hi @dbtlr and @lfades 

Thanks for fixing this issue, I'm relatively new to typescript and wondering how I can apply this change?

currently I an eslint error on this line:

```    
const { Component, pageProps, apollo } = this.props;
```
The error i got looks like this:

```Property 'apollo' does not exist on type 'Readonly<DefaultAppIProps & AppProps<Record<string, string | string[] | undefined>>> & Readonly<{ children?: ReactNode; }>'```

**Comment by lfades** [comment]
@hisea Can you add the `apollo` prop like here ?
```ts
interface Props {
  apollo: ApolloClient<any>;
}

class MyApp extends App<Props> {
```

**Comment by hisea** [comment]
Thank you, it worked well.

sorry for my novice typescript question.
