### ISSUE TITLE
rendering twice when change routes, and routing is passing previous url 

### ISSUE THREAD

**Issue by xpromx** [lfades/next-with-apollo#20]
Hello,

I notice adding in _app.js a console.log(this.props.routes) that is printing twice the router, but the main problem is that first print the previous url and then the current url. it happens using the Link for navigation only.

I have an example project.
https://github.com/xpromx/nextjs-apollo-example

with this problem when I enter to the page /song/:id the first time I'm receiving in the router a diff url with diff params so my query make this error:

```
GraphQL error occurred [getDataFromTree] Error: GraphQL error: Variable "$id" of required type "Int!" was not provided.
```

any ideas?

**Comment by lfades** [comment]
the double render is related to a react-apollo [issue](https://github.com/apollographql/react-apollo/issues/996).

The other issues may be related to one of these:
* The `Link` to the page may not be properly using `href` and `as`.
* `Next.js` had a lot of issues with `react-hot-loader`, specially when doing route navigations, since `Next.js 6.1.0` all of those issues were removed (and react-hot-loader too).

**Comment by Everettss** [comment]
@lfades This is not a problem any of 

- wrong using `href` and `as` in `Link` 
- `react-hot-loader` (I've tried production build with the same results)

But this occurs when you use `getDataFromTree` on the client side and `withRouter`.
Consider to routes `/a` and `/b`

`RouteA`
```javascript
export default function RouteA () {
  return (
    <Link href='/b' as="/b">
      <a>Go to route b</a>
    </Link>
 );
})
```
`RouteB`
```javascript
import { withRouter } from 'next/router'

export default withRouter(function RouteB ({ router }) {
  console.log(router.route);
  // ...
})
```

So when the user on route `/a` click on a link to route `/b` in the console there is output:

```
'/a' // old route in getDataFromTree function
'/a' // old route in getDataFromTree function (doubled?)
'/b' // proprer route name 
```

The proper behavior is printing only `/b`.

**Comment by todesstoss** [comment]
@Everettss, @xpromx `getInitialPprops` is not resolved yet so the `Router` provider still have "old" data, once `gIP` will finish provider will be updated. The solution could be using router data directly form gIP passing 'em down  the tree and not using `withRouter` or use "ssr" option for `getDataFromTree` handling all the loading props manually.
