### ISSUE TITLE
Passing context instead of header to clientFn

### ISSUE THREAD

**Issue by Neitsch** [lfades/next-with-apollo#23]
Hi,
the code I'm currently writing is in an awkward spot: I want to use Apollo's SchemaLink to avoid an extra HTTP request. However, I am also using TypeORM which is heavily decorator based. Apparently, NextJS is not transforming decorators if they are in client-side code but throws an error instead. Of course, I am using the IgnorePlugin for the client side build, but the build is still failing (this is due to the server build of /pages).
Now, my attempt to fix the problem is to create the schema link before calling the handle function, but I am not able to pass the Apollo client to clientFn, because that function only takes the headers as an argument. I'd propose to change https://github.com/lfades/next-with-apollo/blob/master/src/withApollo.tsx#L46 to use ctx instead of headers. I'd be happy to make a PR, just let me know what you think first :)

**Comment by lfades** [comment]
Sure, you can do it, just make sure no breaking chances are introduced, you'll also need to update [this interface](https://github.com/lfades/next-with-apollo/blob/82c1938f59cf3d16814c60c68963ff3343703f5f/src/types.ts#L27). Thank you very much.

**Comment by lfades** [comment]
I can also implement this, seems to be required and makes sense

**Comment by lkbr** [comment]
That would be great. Still unfamiliar with Typescript. 

However, I personally might not need it as my plans above don't work correctly unless I can figure something out: I thought I could get away with only setting `userMeta{ userIp }` on the first SSR, and then client side would pick it up from Apollo's cache, however, Apollo complains on clientside about a missing field because `headers` are missing and thus `userIp` is not set.

**Comment by lfades** [comment]
For SSR you need to directly send the headers cause there's no browser instance, but once you're in the browser you only need to send credentials as usual (like when using `   fetch`)

**Comment by lkbr** [comment]
I don't quite understand, how would I access the ip address from the browser? Do you mind expanding a bit or showing an example?

**Comment by lfades** [comment]
You can use `getInitialProps` to send the `ip` as a prop to the component.

**Comment by lkbr** [comment]
I didn't want to have to set it on every page then have to pass it down multiple components so I thought Apollo local state would be a solution then I could just Query it when I needed. But I got carried away :D. I'll go with your simple suggestion. Thanks!

**Comment by Neitsch** [comment]
Sorry! I completely forgot about it. Will try to get around it early next week. But shouldn't be too hard to get done youself. Maybe a good way to get started with the repo :)

**Comment by lindesvard** [comment]
Would love this as well. For now I just cloned the repo and added: `const apollo = initApollo<TCache>(client, { ctx, headers });`. And works fine 👍 

But my typescript knowledge isn't that good, so hoping for someone to make a PR

**Comment by lfades** [comment]
I'll make a PR in the next hours to tackle this 👍
