### ISSUE TITLE
Use PeerDependency instead of depend on next

### ISSUE THREAD

**Issue by NickBolles** [lfades/next-with-apollo#27]
i just updated to next@7.0 and doing yarn list gives me this

```
yarn list v1.9.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ next-with-apollo@3.1.3
│  └─ next@6.1.2
└─ next@7.0.0
Done in 3.03s.
```

I think that this can be avoided (as well as some bundle sizing issues that I saw too) by making next a [peer-dependency](https://nodejs.org/en/blog/npm/peer-dependencies/) instead of a `dependency` 

you could also add it to dev-dependencies if you want it to be available when  doing dev

Along with all of the types
```
    "@types/graphql": "0.12.7",
    "@types/next": "^6.0.4",
    "@types/prop-types": "^15.5.2",
    "@types/react": "^16.3.14",
```

**Comment by lfades** [comment]
Makes a lot of sense, do you want to do a PR ?.

**Comment by NickBolles** [comment]
Sure. I can try to put one together tonight.
