### ISSUE TITLE
Have an actual example

### ISSUE THREAD

**Issue by zefexdeveloper** [lfades/next-with-apollo#33]
It would be nice to have an actual example of using the HOC, perhaps recreating the https://github.com/zeit/next.js/tree/canary/examples/with-apollo example and setting it in an example folder or even sending as PR to the next.js repository.

**Comment by lfades** [comment]
Cool, I'll consider doing this, a folder with an example will do the job.

**Comment by Victorkangsh** [comment]
It’s best to have a demo on how to use ctx and headers. I’m not very clear about this. Very nice project!

**Comment by Pricelsss5386** [comment]
This would be fantastic, as a newer web developer, i am struggling finding a starter template that uses, Nextjs, Apollo, React all with Typescript.

**Comment by axe-z** [comment]
exactly, this is a bit abstract to be left without a working exemple.

**Comment by rob-gordon** [comment]
+1

**Comment by lfades** [comment]
Hi Guys, [this implementation](https://github.com/wesbos/Advanced-React/blob/master/finished-application/frontend/lib/withData.js) is from a working app that comes in the [Advanced React](https://advancedreact.com/) course of @wesbos, do you guys think that it's enough or another example is required ?

Another very simple example from one of my projects: [zemoga-ui-test](https://github.com/lfades/zemoga-ui-test/blob/master/app/lib/withApollo.js), it's running here: https://zemoga-ui-app-dtqgzzsbnp.now.sh/
