### ISSUE TITLE
Conditional Rendering Forces Data Loading on Client Side

### ISSUE THREAD

**Issue by mattfwood** [lfades/next-with-apollo#36]
DEMO REPO: https://github.com/mattfwood/next-apollo-issue
LIVE EXAMPLE: https://advanced-react-frontend.herokuapp.com/orders
- To recreate, create an account and try to go to a "restricted" page like `/orders`

I've been stuck on this issue for 8+ hours with absolutely no luck.

For context, I'm following [this course](https://advancedreact.com/) and I've asked for help on that end as well, but I'm starting to think it might be a limitation / issue with either this package or NextJS itself.

I have this [wrapper component](https://github.com/mattfwood/next-apollo-issue/blob/master/components/PleaseSignIn.js) that I'm using to check if certain views are authenticated.

Basically, it looks like if I'm using a wrapper component like this, it causes data to be forced to be fetched on the client side, causing the loading state "flash" that NextJS is typically designed to avoid.

I'm guessing that there's an issue between `next-with-apollo` fetching the data and NextJS knowing if it should be rendering the `SignIn` component or the children. It does eventually get hydrated when the page loads, but it still causes that "flash" of the incorrect state, which means that any view that's "protected" in this way would flash a login screen.

The only error that NextJS is emitting that is this:
`[Network error]: SyntaxError: Unexpected token N in JSON at position 0`

I know that this means that some request to my server is returning HTML instead of JSON, but when I check my server logs there isn't any request that's returning HTML. And I know my endpoints are correct because all the other data eventually gets loaded, but only after it's mounted. It looks like the request only fails on the server side (which is why it's only being shown in the NextJS logs).

Here's a list of additional observations after struggling with this for almost two full days:
- It only happens if the page you initially load has the wrapper component. Meaning if you go to a non-protected page and then click to a restricted page, it doesn't "flash"
- It doesn't seem to happen when running in development, only in production (doing `next build` and `next start` as opposed to `next`).

**Comment by mattfwood** [comment]
After testing many different things, I've narrowed it down to this:

For some reason, it looks like all serverside data requests by apollo are being made to the _root_ of the current domain, instead of the URI endpoint. I really can't track down why this is happening. I thought that maybe I had an extra `/` in my URI but that wasn't the case.

**Comment by lfades** [comment]
Hello!, I may take time to run your repo in the weekend, unfortunately I'm kinda busy right now, in the meantime, I think you can't use `process.env` in the client, it may work in SSR but not in the browser. (see [here](https://github.com/mattfwood/next-apollo-issue/blob/35f6ddd443dbec46deafc349fdc292e7efeb6e62/lib/withData.js#L8)), also check that you're properly receiving the headers for both SSR and browser.

**Comment by mattfwood** [comment]
@lfades Totally understand, I appreciate the reply!

Turns out it was somewhat unrelated, I'd jumped all over the place. I think NextJS or my GraphQL server was swallowing errors and making it impossible to debug this, but it ended up being an issue with some CORS problems that weren't being logged out.

It seems to be something where CORS / credentials don't work when requested from the server, but work when the request is made from the client.

I'll keep looking to see if I can get a more specific explanation in case someone else runs into this, but I'll close for now.
