### ISSUE TITLE
CTX undefined

### ISSUE THREAD

**Issue by dustinbrink** [lfades/next-with-apollo#38]
Trying to use your example with apollo-boost while setting an authorization header, but contect ctx always seems to be undefined? 

How do I require context while still using your HOC?

```
// apollo.js
import withApollo from 'next-with-apollo';
import ApolloClient from 'apollo-boost';
import getConfig from 'next/config';
import { getCookieJwt } from './auth';

const { publicRuntimeConfig } = getConfig();

export default withApollo(
  ({ ctx, headers }) => {
    return new ApolloClient({
      uri: `${publicRuntimeConfig.SERVER_URL}/api`,
      request: async operation => {
        const token = await getCookieJwt(ctx); //ctx is undefined
        operation.setContext({
          headers: {
            authorization: token ? `Bearer ${token}` : ''
          }
        });
      }
    });
  },
);
```

**Comment by lfades** [comment]
> withApollo accepts a function that receives { ctx, headers } or { initialState } depending on whether it's running in SSR or not and returns an ApolloClient.

`ctx` and `headers` are undefined in the client because those are SSR only options, in the client use the `credentials` option or `document.cookie`.

**Comment by WickyNilliams** [comment]
I am seeing instances where `process.browser` is undefined _and_ `ctx` is undefined? Why is this?

**Comment by WickyNilliams** [comment]
I guess I should just settle on this:

```js
const result = ctx
  ? doSomethingServerSide(ctx)
  : doSomethingClientSide();
```

Instead of what I was trying:

```js
const result = process.browser
  ? doSomethingServerSide(ctx)
  : doSomethingClientSide();
```

Is that right?

**Comment by lfades** [comment]
@WickyNilliams It's better if you check for `ctx.req` because `ctx` is not empty in the browser, it just doesn't have access to the request and response.

```js
const result = ctx.req
  ? doSomethingServerSide(ctx)
  : doSomethingClientSide(ctx);
```

**Comment by WickyNilliams** [comment]
Hmm... but you explicitly _don't_ pass it on client, right?

**Comment by lfades** [comment]
Yes I do, but only once, because after that the same client is used.

**Comment by WickyNilliams** [comment]
hmmm so i should do `ctx && ctx.req` as a check?

**Comment by WickyNilliams** [comment]
Honestly, I feel like something more explicit would be better than inferring whether browser or not like this.

**Comment by coommark** [comment]
Two days! Exactly two effing days I spent trying to solve this issue. Because credentials don't work on SSR! Then I stumbled on this, and here is my final piece:

```
export default withApollo(
    ({ ctx, headers, initialState }) => {
        return new ApolloClient({
            uri: "http://localhost:8080/api/graphql",
            request: async operation => {
            const authData = process.browser
                ? getUserFromLocalCookie()
                : getUserFromServerCookie(ctx.req);
            let token = null;
            if(authData) {
                token = authData.extra.payload.token;
            }
            operation.setContext({
                headers: {
                    bearer: token ? `${token}` : ''
                }
            });
            }
        });
    },
);
```

**Comment by willowHR** [comment]
Following on this, I too see that CTX isn't always set on server:

!!ctx:  false
process.browser:  false

Should I be able to rely on CTX on the server? It is required for me to set up the URL and bearer token.

**Comment by lfades** [comment]
@willowHR `ctx` should be available in the server, always, if that's not the case please share a codesandbox with me 🙏

**Comment by willowHR** [comment]
@lfades 

See repo here:
https://codesandbox.io/embed/hello-world-0j8fi

If you check the terminal output - you see that 
browser = false, but ctx = false on the second call to the server.

**Comment by lfades** [comment]
@willowHR Thank you for the repro, I can see the issue now, adding a fix 👌

**Comment by lfades** [comment]
@willowHR Can you try it again please 🙏  use the v4.1.1

**Comment by willowHR** [comment]
It has added the ctx - so yes looks like it addressed the problem. 
I do now have a new warning in the console below - though its unclear how this should be related to this fix, so ill continue to investigate. Posting here in case it makes sense to you (I don't get this error using the next example implementation)

index.js:1 Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format.
