### ISSUE TITLE
Access Apollo client instance inside getInitialProps

### ISSUE THREAD

**Issue by alaister** [lfades/next-with-apollo#4]
Is there currently a way to access the apollo client instance inside of a components getInitialProps?
One approach to take would be to pass the apollo client instance in as the second parameter as done in the [apollo example on next.js](https://github.com/zeit/next.js/blob/canary/examples/with-apollo-auth/pages/index.js#L10).

**Comment by lfades** [comment]
That's possible, I can do that today, just keep in mind that it'll only work for the first `getInitialProps` after apollo

**Comment by lfades** [comment]
Also, it would be the instance without the state, because to fetch the state with `getDataFromTree` I need to have the childs props

**Comment by lfades** [comment]
[Done](https://github.com/lfades/next-with-apollo/commit/05e3323b7359d5b5d697db8c9966c9510653115a)
