### ISSUE TITLE
forward "set-cookie" when SSR occurs

### ISSUE THREAD

**Issue by gmadar** [lfades/next-with-apollo#41]
forwarding cookies from `Next` to `Apollo` works as expected
But  the other way around doesn't work for me.

When my Apollo server is returning a "set-cookie" header it is not returned from `Next`

Is there a way to forward the "set-cookie" header when SSR occurs?

**Comment by gmadar** [comment]
What I did in the meantime is pass a custom fetch function with an interceptor of the result. if the result has a 'set-cookie' header it adds it to the ctx response using the [nookies](https://github.com/maticzav/nookies) package

**Comment by lfades** [comment]
Hello, I don't recommend to try to set cookies during SSR, there's no browser instance, what's your use case ?

**Comment by gmadar** [comment]
my use case:
A facebook signup which result in a set cookie for  having a session.
the user is landing back from facebook with the token.
I can do the sign up on the browser but I prefer to do it directly on the server.
I only use the set cookie when the process.browser is falsy

**Comment by lfades** [comment]
Hello, this will do the work inside `getInitialProps` 👍 
```js
function setToken({ res } = {}, cookieName, value) {
  if (process.browser) return

  res.setHeader(
    'Set-Cookie',
    require('cookie').serialize('loginToken', token, {
      path: '/learn',
      expires: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
      httpOnly: false
    })
  )
}
```
