### ISSUE TITLE
No Persistant cache for local queries

### ISSUE THREAD

**Issue by HeadFox** [lfades/next-with-apollo#42]
Hi ! :) 
I didn't find why I can't have Persistant cache with your library. 
I tried to setup all by myself instead but have so many errors.

Do you have an idea ?
I saw on some issues that I need to setup persist cache before init Apollo.

Thanks !

**Comment by lfades** [comment]
Hello, this library only adds the Apollo client and does SSR for you by prefetching all queries, persistent cache can be done with Apollo in other ways, like: https://github.com/apollographql/apollo-cache-persist. Just keep in mind that Next.js does SSR and it may not be that easy for that case.

**Comment by HeadFox** [comment]
I added persistant storage by adding persistCache to _app.jsx and componentDidMount to async.
So we wait cache to be restored before redering. We get the cache from the apollo props client.

## _app.jsx
```javascript
import React from 'react';
import App from 'next/app';
import { ThemeProvider } from 'react-jss';
import { ApolloProvider } from 'react-apollo';
import withApollo from '@libs/apollo/withApollo';
import theme from '@styles/themes/main.theme';
import { persistCache } from 'apollo-cache-persist';

class Website extends App {
  state = {
    loaded: false,
  };

  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }

    return { pageProps };
  }

  async componentDidMount() {
    const { apollo } = this.props;
    try {
      // See above for additional options, including other storage providers.
      await persistCache({
        cache: apollo.cache,
        storage: window.localStorage,
      });
    } catch (error) {
      console.error('Error restoring Apollo cache', error);
    }
    const style = document.getElementById('server-side-styles');

    if (style) {
      style.parentNode.removeChild(style);
    }
    this.setState({
      loaded: true,
    });
  }

  render() {
    const { Component, pageProps, apollo } = this.props;
    const { loaded } = this.state;

    if (!loaded) {
      return <div>Loading...</div>;
    }

    return (
      <ApolloProvider client={apollo}>
        <ThemeProvider theme={theme}>
          <Component {...pageProps} />
        </ThemeProvider>
      </ApolloProvider>
    );
  }
}

export default withApollo(Website);
```

**Comment by lfades** [comment]
Is it working or are you getting any errors ?, btw keep in mind that you're not having any SSR by doing that. Do you need to always restore the cache ?

**Comment by HeadFox** [comment]
You are right, I spend so much times on this that I forgot this problem.
What I want is to store language. When user change language, I store it into cache and I want to restore it after refresh. But I think using apollo is not the good way. Maybe I will try context API or redux. What do you think about it ?

**Comment by lfades** [comment]
If you just want to store the language, use a cookie, that way you can update the language before render, otherwise you'll see the language being updated after render.

**Comment by HeadFox** [comment]
Okay thanks !! We discover that next-i18next already use cookies so we just get them after language and then set our default clientState to that value.

**Comment by krish-dev** [comment]
@lfades I understand that apollo-cache-persist is not easy to implement. However, this is very much important for Nextjs PWA application. Do you have any idea, how to use apollo-cache-persist using this lib?
