### ISSUE TITLE
GraphQL error occurred [getDataFromTree] TypeError: Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by remy** [lfades/next-with-apollo#46]
I've got a very small `withData.js` [script](https://gist.github.com/remy/faae63f3d8238cbb6ea2b6fc8dea0f45) and using with next@7.0.2, and I'm constantly seeing the following error both on the server side and the client side:

```
GraphQL error occurred [getDataFromTree] TypeError: Cannot read property 'current' of undefined
    at ReactDOMServerRenderer.read (app/node_modules/next-with-apollo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3067:49)
    at renderToStaticMarkup (app/node_modules/next-with-apollo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3604:27)
    at process (app/node_modules/next-with-apollo/node_modules/react-apollo/react-apollo.umd.js:118:24)
```

I've got a suspicion that it's not really the next-with-apollo that's causing it, but I honestly don't know where to start to debug it.

Any idea?

**Comment by lfades** [comment]
That error is from [here](https://github.com/lfades/next-with-apollo/blob/master/src/withApollo.tsx#L76) but it can be a bug in a component, `current` looks like it may be from a reference (`React.createRef`)

**Comment by remy** [comment]
The `createRef` isn't happening anywhere in my code during this error. I do use the function, but I'm seeing the error on every page load regardless of whether I'm using createRef.

Have you got any tips on how to dig into this further? I don't very much about `getDataFromTree`, but keen to resolve my issue (and I'm sure it's to do with a combination of the code I've written and then using `next-with-apollo`).

**Comment by remy** [comment]
Weirdly solved it.

I was doing a redirect inside the `_app.js` render method which on the server side appears to have all kinds of weird consequences, including the error that I reported here.

Just in case anyone comes across this with a similar issue, I also had:

- styled-components complaining about server side classes not matching client side
- occasionally `__NEXT_DATA__` was missing on the server and throwing

The solution was to ensure the redirect *only* happened in the client side (in the render function - in `getInitialProps` it's safe on both client and server).
