### ISSUE TITLE
Desired behavior?

### ISSUE THREAD

**Issue by Emiliano-Bucci** [lfades/next-with-apollo#47]
Hi, i was looking into some examples using something similar to this HOC, and i noticed that on every page change, is like all the App component is being unmounted and then mounted again (while in the normal Next.JS link navigation or other With-Apollo similar examples this doesn't happend). Is this normal? 
Thanks!

**Comment by lfades** [comment]
Hello, that's not a desired behavior, do you have a reproduction of the issue that I can take a look into ?
