### ISSUE TITLE
Use client.query on front-end part

### ISSUE THREAD

**Issue by HeadFox** [lfades/next-with-apollo#48]
Hi !

I would like to know if it's possible to use withApollo on front-end part, in componentDidMount for example. I don't like the react-apollo jsx. So I prefer to use client.query(). Do you know if it's possible ?

**Comment by lfades** [comment]
Yeah, use the [withApollo HOC] from Apollo.(https://www.apollographql.com/docs/react/api/react-apollo.html#withApollo)
