### ISSUE TITLE
Forward cookies from client

### ISSUE THREAD

**Issue by alaister** [lfades/next-with-apollo#5]
Thanks for the quick resolution of the last issue :)
I am currently using regular old cookies for my sessions and I'm wondering if there is a way to "forward" them on from my Next server to my backend graphql server?

My apollo boost is currently configured to send cookies as follows:
```javascript
fetchOptions: {
    credentials: 'same-origin'
}
```
This means when the request comes from the frontend my graphql server gets the cookie as it is supposed to. When the request is sent from the backend, however, the cookie is in `context.req.headers.cookie` which doesn't seem to be sent to the graphql server.
Would the easiest way be to set the cookie header on the server side to `context.req.headers.cookie` for each server side request?

Thanks

**Comment by lfades** [comment]
That's right, `credentials: 'same-origin'` works fine if you're doing the request from the browser, but on SSR you don't have access to the browser, you're prefetching the page and sending it in the `response`, but the browser doesn't exists in that process.

for SSR the only thing you need to do is send the cookie as a header, here's the example from docs:
```js
http: ({ headers }) => {
  if (!process.browser && headers) {
    headers.ssr = '1'
  }

  return new HttpLink({
    uri: GRAPHQL_URL,
    credentials: 'same-origin',
    headers // send the headers with the cookie inside
  })
}
```

For apollo-boost however, I'm not sure if that's currently possible, you can't send headers to their [HttpLink](https://github.com/apollographql/apollo-client/blob/master/packages/apollo-boost/src/index.ts#L74), there's an [issue](https://github.com/apollographql/apollo-client/pull/3098) about it

**Comment by alaister** [comment]
I have reverted to using the regular links and it works like a charm - Thank you!

**Comment by pablohenriq** [comment]
@alaister how exactly did you do that? Could you post a snippet of code, please?
