### ISSUE TITLE
Use with local state management [Apollo client 2.5]

### ISSUE THREAD

**Issue by shipcake** [lfades/next-with-apollo#54]
hi,
i setup project For friendly SEO correct the data. next-with-apollo great for me.

But Today i think about Local state management Because i want to use the couple state management . I don't idea to work it. the guideline document in apollographql website not implement in Nextjs i can't Set local state in my project.

please suggestion for me to use a couple modules.
thank you

**Comment by lfades** [comment]
Hi @shipcake, do you have an implementation for it already and it's not working or you don't know how to do it ?

**Comment by shipcake** [comment]
i dont know how to pass mutation for change cache

**Comment by lfades** [comment]
@shipcake Follow this guide: https://www.apollographql.com/docs/react/essentials/local-state.html

**Comment by shipcake** [comment]
const client = new ApolloClient  in document different in your module. how to access client const in diferent page?

**Comment by lfades** [comment]
@shipcake I think I ended up missing the notification for your last question, I'm sorry, if you still have any issues please don't hesitate in commenting again.

**Comment by jxwolstenholme** [comment]
@lfades Apologies for dragging this up again - I have the same question?
Is there by any chance a working example of how to access and write to the client store as per the Apollo react docs? [https://www.apollographql.com/docs/react/data/local-state/](https://www.apollographql.com/docs/react/data/local-state/)
I can't seem to follow how to jump from the next-with-apollo docs to what is being implemented in  the apollo docs.
