### ISSUE TITLE
Could we enable operations on the apollo cache (during SSR) before extracting initialState?

### ISSUE THREAD

**Issue by SevenInitiative** [lfades/next-with-apollo#57]
Hi there,

Don't know if this is unusual requirement or not, but here is what I'd like to be able to do:

Using the next-with-apollo HOC works a treat with all my queries to an Apollo Server, but I also have client state that needs to be set in the Apollo Client cache based on the data that is collected in getDataFromTree. For example, I run a query to get a set of addresses from my graphql API but then I need to be able to set the default address as the selected one in the Apollo Client local state. If I wait until the client renders the update to make this updates (via mutations) then I see a flash of server rendered content with the data from my graphql API before seeing the client state take effect.

I initially thought I had the power to fix this and have my client / local state defaulted corrected as part of the SSR (as I can access the cache and the initialState in the clientFn that I configure the withApollo HOC with). But I found that this wasn't working (my components rendered as though all they had access to was the back-end data). Here is some semi-psuedo code showing what I was doing:

```js
const initializeClientData = cache => {
    // Run some queries against the cache and (based
    // on that data) return data to write to the cache.
    // I want this to be added to the initialState.
    try {
        const getAddresses = { query: GET_ADDRESSES };
        const { addresses = [] } = cache.readQuery(getAddresses);
        return {
            selectedAddress: addresses.find(({ isDefault }) => !!isDefault) || null
        };
    } catch (e) {
        return {};
    }
}

export default withApollo(
    ({ initialState }) => {
        // Do ApolloClient link config things.

        const cache = new InMemoryCache().restore(initialState || {});
        const data = initializeClientData(cache);
        cache.writeData({ data });

        // Do more things.

        return new ApolloClient({
            cache,
            ...otherThings
        });
    }
)
```

When debugging this I found that my updates to the cache (which I make in the clientFn) were indeed happening... but were being overwritten. The getClient function (when it runs in the withApollo constructor) overwrites my updates to the cache with the initialState (which is calculated before my cache.writeData() changes are applied), erasing the additional data that I have written to it in my clientFn:

https://github.com/lfades/next-with-apollo/blob/master/src/withApollo.tsx#L104
https://github.com/lfades/next-with-apollo/blob/master/src/apollo.ts#L42

Proposed solution (please forgive the lack of TypeScript):

I want to be able to run updates on the cache when server-rendering (in the getInitialProps of the withApollo HOC) after doing the getDataFromTree but before the cache data is extracted and set as the apolloState.data (initialState). I need the ability to operate on the cache here:

https://github.com/lfades/next-with-apollo/blob/master/src/withApollo.tsx#L83

I've gotten this to work nicely by adding an optional function to the options (which I have tentatively called "initializeClientData") that is passed the cache (so it can perform whatever operations are needed) before the initialState is extracted from it. It works on my machine... gives me the ability to SSR my app with all of the client state correctly set based on the back-end data fetched in getDataFromTree.

```js
if (options.getDataFromTree === 'always' || (options.getDataFromTree === 'ssr' && ssrMode)) {
    try {
        await getDataFromTree(
            <App
                {...appProps}
                Component={Component}
                router={router}
                apolloState={apolloState}
                apollo={apollo}
            />
        );
    } catch (error) {
        // Prevent Apollo Client GraphQL errors from crashing SSR.
        if (process.env.NODE_ENV !== 'production') {
            // tslint:disable-next-line no-console This is a necessary debugging log
            console.error('GraphQL error occurred [getDataFromTree]', error);
        }
    }

    if (typeof options.initializeClientData === 'function') {
        await options.initializeClientData(apollo.cache);
    }

    if (ssrMode) {
        // getDataFromTree does not call componentWillUnmount
        // head side effect therefore need to be cleared manually
        Head.rewind();
    }

    apolloState.data = apollo.cache.extract();
}
```

Any thoughts on this proposal? Would you be happy for me to PR this update?

**Comment by lfades** [comment]
@SevenInitiative How is the cache here:
```js
await options.initializeClientData(apollo.cache);
```
different from the cache that you receive after this in the second call that has the `initialState`:
```js
const cache = new InMemoryCache().restore(initialState || {});
```

**Comment by SevenInitiative** [comment]
@lfades I think the difference, which is affecting me, is that a function that can operate on the cache in the getInitialProps prior to the cache extraction means that initialState includes my updates for when the app is then rendered server side. If I do these operations in the clientFn then they do not appear to be applied before the SSR occurs -- and those changes have to be reapplied on the client and a re-render forced.

I'll spend a bit more time this morning to make sure I am understanding the problem.

**Comment by SevenInitiative** [comment]
@lfades double checked and this problem I'm having can't be solved in the clientFn. I think the main reason for this is because of this line. When the clientFn is run (in which my cache updates occur) the cache is immediately overwritten by this line which reverts the cache to the value of the initialState:

https://github.com/lfades/next-with-apollo/blob/master/src/apollo.ts#L42

The initialState prop only includes the data fetched in getDataFromTree (not my cache updates).

I suspect that my original suggestion might be the wrong way to solve this problem. Instead, I think consumers of next-with-apollo need to be able to declare that they are creating their own cache and are, themselves, restoring it with the initialState. This declaration should prevent this line from running...

```ts
function getClient<TCache>(
  clientFn: InitApolloClient<TCache>,
  options: InitApolloOptions<TCache> = {}
) {
  if (typeof clientFn !== 'function') {
    throw new Error(
      '[withApollo] requires a function that returns an ApolloClient'
    );
  }

  const client = clientFn(options);

  if (options.initialState && !options.leaveMyCacheAlone) client.cache.restore(options.initialState);

  return client;
}
```

That would allow me to restore the cache and then query or write to it in the clientFn.

If you think I am missing something please let me know.

**Comment by lfades** [comment]
@SevenInitiative What if the restore cache get's the cache from your client instead of from `options` ? Idk but it may work better.

**Comment by SevenInitiative** [comment]
Might be misunderstanding... but do you mean...

Replacing this line:
`if (options.initialState && !options.leaveMyCacheAlone) client.cache.restore(options.initialState);`

With this:
`client.cache.restore(client.cache.extract());`

I assume that would be redundant -- unless restore is doing something I'm unaware of? I guessed that this line is here for consumers who don't do the restore step in their own clientFn, in which case this would be a breaking change for them... and it would only help in my case because it's now doing nothing.

**Comment by lfades** [comment]
@SevenInitiative So the thing is, that line may be able to be removed entirely, it's there just for backwards compatibility, but if you check the readme it does restore from the user function's first. What do you think ? I'll create a major version soon because Next.js will release official typescript support (with official types of course) and I want to add them to the project once it's released.
