### ISSUE TITLE
can't use setstate when use <Link> second page

### ISSUE THREAD

**Issue by shipcake** [lfades/next-with-apollo#59]
the first page a <Link> will receive data from graphql. second time I clicked <Link> nextjs not render the new data from graphql (another link) but the same link same data in previous creche render correctly. please see the capture screen 
https://media.giphy.com/media/eMUztsvqbousK4yyQV/giphy.gif

ps. I receive data from {data} render will completed but second page graphql not load = can't set state onCompleted={}
`<Query query={QUER_DATA_EDIT} variables={{ id }} onCompleted={(data) => this.setData(data.edit_categories[0].data[0])}>
                {({ data, loading, error }) => {
                    if (loading) return <Loader_Component />
                    if (data) return Render_edit(data)
                }}
</Query>`

**Comment by lfades** [comment]
@shipcake I'm not sure I follow, can you give me more details ? a reproduction can help, does the second page works by itself with a page refresh without a navigation ?
