### ISSUE TITLE
Material-UI v4 display warnings when used with next-with-apollo

### ISSUE THREAD

**Issue by ralvs** [lfades/next-with-apollo#60]
Related issue at MUI repository: [#15798](https://github.com/mui-org/material-ui/issues/15798#issuecomment-497307134)

After update to Material-UI v4.0, lots of warnings started to show at DevTools.
If I remove `next-with-apollo` and follow the example [with-apollo-auth](https://github.com/zeit/next.js/tree/master/examples/with-apollo-auth), everything works fine.

**Comment by eps1lon** [comment]
Issue is likely caused by bundling a polyfill which relies on the `window` object. `window` should be undefined on the server IMO.

**Comment by oliviertassinari** [comment]
I believe I have identified the source of the problem:
 https://github.com/mui-org/material-ui/issues/15798#issuecomment-497980950

**Comment by ivawzh** [comment]
Also after I set `withApollo(..., { getDataFromTree: 'never' })` and `new ApolloClient({ ssrMode: false, ... })`, the warnings still persist.

**Comment by oliviertassinari** [comment]
@ivawzh I have experienced the opposite. It solves the warning in the reproduction provided on Material-UI side.

**Comment by willowHR** [comment]
Im experiencing the same as here, setting ```withApollo(..., { getDataFromTree: 'never' })``` has no impact on the warnings. 
Following the next repository example does not exhibit this error. Ill continue to dig into the differences, but there is an incompatibility between this library and material-ui currently.

**Comment by nicovalencia** [comment]
Make sure you're getting what you're expecting from the re-render, but if you're looking for the happy path SSR hydration, this should work:

```
export default withApollo(createClient, { getDataFromTree: 'ssr' });
```

**Comment by wesbos** [comment]
This can be closed

**Comment by vitaliemiron** [comment]
now withApollo function have another interface, can you post please new example how to fix this?
