### ISSUE TITLE
feature request: add support for @apollo/react-hooks

### ISSUE THREAD

**Issue by adamsoffer** [lfades/next-with-apollo#62]
Awesome library. I like how this implementation wraps `_app.js` so you don't have to explicitly wrap every page. I maintain a similar library and [just added support](https://github.com/adamsoffer/next-apollo/tree/v3.0.0-beta.5) for `@apollo/react-hooks`. I'd love to see it implemented here as well!

**Comment by lfades** [comment]
Hi @adamsoffer, I'm planning on doing a release after the release of `Next,js 9`, which will include Typescript types and other small changes, surely I can include this, is that the official way of doing hooks in Apollo or just a temporal solution ?

**Comment by adamsoffer** [comment]
Awesome! Yeah that's the official way of doing hooks in Apollo. https://www.npmjs.com/package/@apollo/react-hooks

**Comment by adamsoffer** [comment]
@lfades - here are the changes required to support the official apollo hooks FYI. https://github.com/adamsoffer/next-with-apollo/commit/ee8047d0d6c55dbe74df37641eddf0a871bc66a7

**Comment by wtgtybhertgeghgtwtg** [comment]
Once a release with https://github.com/apollographql/react-apollo/pull/3168 lands, both `@apollo/react-hooks` and `react-apollo` will use the same package, `@apollo/react-ssr`.  So I guess you'd just use that here.

**Comment by corysimmons** [comment]
@lfades Next9 landed and is really nice. Combined with Apollo's official (if currently undocumented) hooks lib, next-with-apollo would be such a nice setup.

@wtgtybhertgeghgtwtg that landed

**Comment by lfades** [comment]
Hi there, I'm currently working on some updates after the release of Next.js 9, once that's ready I'll update the package 😄

**Comment by corysimmons** [comment]
Awesome, thank you!

**Comment by lfades** [comment]
I'm updating the package now, will update today.

**Comment by lfades** [comment]
I created the PR here: https://github.com/lfades/next-with-apollo/pull/63

@corysimmons @adamsoffer If I add @apollo/react-hooks will that break the package for users of `react-apollo` ?

**Comment by wtgtybhertgeghgtwtg** [comment]
Try using the underlying `@apollo/react-ssr` to support both.

**Comment by corysimmons** [comment]
@lfades ^ What he said.

**Comment by lfades** [comment]
Adding `@apollo/react-ssr` alone should work, I only need `getDataFromTree` so no need for `@apollo/react-hooks` and users would be able to use either `react-apollo` or `@apollo/react-hooks`. There's one issue though,  `@apollo/react-ssr` is not published in npm....lol

**Comment by corysimmons** [comment]
Fork/publish it yourself as npm.im/apollo-react-ssr or something, then when they publish you can archive yours and use theirs?
