### ISSUE TITLE
page render() called twice after this HOC applied

### ISSUE THREAD

**Issue by yxwu** [lfades/next-with-apollo#65]
Hi, once I applied this HOC, even the simplest page will be rendered twice during client navigation. 
I tried the latest version 4.0.0 with next.js 9.0.2, and this issue also exists with previous version.
Anyone know how to fix this issue?

Thanks

**Comment by lfades** [comment]
Hi @yxwu, Unfortunately I think this is an issue with the Apollo packages, are you using `@apollo/react-hooks`?

**Comment by NikoMontana** [comment]
@yxwu 

> Note: Do not be alarmed that you see two renders being executed. Apollo recursively traverses the React render tree looking for Apollo query components. When it has done that, it fetches all these queries and then passes the result to a cache. This cache is then used to render the data on the server side (another React render). 

* https://github.com/zeit/next.js/tree/master/examples/with-apollo
* https://www.apollographql.com/docs/react/features/server-side-rendering/#getDataFromTree

**Comment by yxwu** [comment]
Hi @NikoMontana, thanks a lot, that explained.
