### ISSUE TITLE
Doesn't work with @apollo/react-hooks

### ISSUE THREAD

**Issue by PabloSzx** [lfades/next-with-apollo#67]
Following all the examples and it says it should work but it doesn't, all i get is `Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.`
I made a repository as template with the error https://github.com/PabloSzx/Next9-Apollo-Typescript

The GraphQL instance is working as intended
<img width="960" alt="chrome_IoBtToNShL" src="https://user-images.githubusercontent.com/8672915/61589120-b6531e00-ab73-11e9-93d5-b62eb11e8b12.png">

**Comment by PabloSzx** [comment]
`@apollo/react-hooks` doesn't specify this anywhere, but i found it in a example. 

You have to use the `ApolloProvider` from `@apollo/react-hooks` itself, not from the "react-apollo" package.
https://github.com/apollographql/react-apollo/blob/release-3.0.0/examples/hooks/client/src/index.tsx

```typescript
import { ApolloProvider } from "@apollo/react-hooks";
```

This could be be mentioned in this documentation so this simple error doesn't happen anymore.

**Comment by lfades** [comment]
@PabloSzx I'm sorry about that, @robertcoopercode added a PR and now the docs are updated 🙏
