### ISSUE TITLE
Preloading data not working on ssr nor client-side-routing

### ISSUE THREAD

**Issue by timojokinen** [lfades/next-with-apollo#69]
Hi i just tried this library and I'm running into the same issue described here https://github.com/lfades/next-with-apollo/issues/37.

It doesn't matter if I set 'always', 'never' or 'ssr' as the 'getDataFromTree' option. The result is always the same. The page is rendered before the data was loaded and the request to load the data happens on client side every time.

I created a small sample repo:
https://github.com/timojokinen/next-pokemon

The backend I used is this:
https://github.com/lucasbento/graphql-pokemon

I can't seem to find out what the problem is, I followed the instructions in the readme.

**Comment by lfades** [comment]
@timojokinen Thanks for the report, I'll be taking a look soon

**Comment by timojokinen** [comment]
Thanks! Have you already had time to look into it?

**Comment by jordykoppen** [comment]
I'm experiencing the exact same issue. 
`next: 9.0.2` `apollo-boost: 0.4.3` `next-with-apollo: 4.1.1`

**Comment by jordykoppen** [comment]
I currently worked around the problem by using `3.4.0`. It works jut fine even though the README mentions using latest. Will I be missing out on something significant by using that version for now? @lfades

**Comment by lfades** [comment]
@jordykoppen Are you using `react-apollo` or `@apollo/react-hooks`? I'm not sure of where the issue can be, I'll try to reproduce it by myself using both 🤔

**Comment by jordykoppen** [comment]
@lfades Assuming this is regarding my first reply, I'm using `react-apollo: 2.5.8`. If there's anything I can help with or something I can try out, let me know, I'd love to help :)

**Comment by lfades** [comment]
@jordykoppen I can confirm that the issue is `@apollo/react-ssr`, it's not working with `react-apollo`, now I need to figure out how to solve it.
