### ISSUE TITLE
apolloClient is null in /pages

### ISSUE THREAD

**Issue by ivorpad** [lfades/next-with-apollo#76]
Here's a codesandbox: https://codesandbox.io/embed/hello-world-hspow

I followed the documentation but I'm still unable to access `apolloClient` from the pages props.

What am I missing?

Relevant file `index.js`

```javascript
import Link from "next/link";
function Index(props) {
 
  console.log(props); // apolloClient: null

  return (
    <div>
      Hello World.{" "}
      <Link href="/about">
        <a>About</a>
      </Link>
    </div>
  );
}

Index.getInitialProps = async function(ctx) {
  const apolloClient = ctx.apolloClient;
  return { apolloClient };
};

export default Index;
```

**Comment by lfades** [comment]
@ivorpad You can access the client in the context of `getInitialProps`, but you should not return it as a prop, it will not work because `getInitialProps` should return a valid JSON, if you want to access the client in the page use `ApolloConsumer`

**Comment by ivorpad** [comment]
True. I don't know what I was thinking 👍  

This solved my issue:

```javascript
Index.getInitialProps = async function(ctx) {
  const apolloClient = ctx.apolloClient;
 const state = apollocClient.extract();
  return { state };
};
```

Thanks.
