### ISSUE TITLE
Update implementation to use AppTree

### ISSUE THREAD

**Issue by adamsoffer** [lfades/next-with-apollo#78]
Currently, if you try using `useRouter` with this library next will throw an error. Next now provides `AppTree` to getInitialProps for getDataFromTree. This allows us to use `useRouter` when calling getDataFromTree by providing an AppContainer that provides the context in the render tree. 

Check out how next updated the official next apollo example here: zeit/next.js@dc9e270

**Comment by qw-in** [comment]
This should be done as of 4.3.0
