### ISSUE TITLE
[4.3.0] getDataFromTree always issue (client side prefetch)

### ISSUE THREAD

**Issue by qw-in** [lfades/next-with-apollo#81]
When using the default config or setting `{ getDataFromTree: 'always' }` client side prefetching won't work

```
GraphQL error occurred [getDataFromTree] Invariant Violation: ReactDOMServer does not yet support Suspense.
```

Reproducible here: https://y8ltr.sse.codesandbox.io/
Code for above: https://codesandbox.io/s/next-with-apollo-y8ltr

Unfortunately beyond removing support  for the feature there does not seem to be an obvious solution

There is an open issue on the next.js repo here https://github.com/zeit/next.js/issues/8289

If you rely on it I would recommend sticking with `4.2.0` for now

**Comment by lfades** [comment]
@qw-in This is probably an issue with Apollo, the `getDataFromTree` from `@apollo/react-hooks` is probably not the same implementation

**Comment by ceefour** [comment]
I also got this issue.

I wonder what is the best course (or workaround) here? I'm new to both Next.js and Apollo and hybrid CSR+SSR...

Is the plan to "fix" next-with-apollo on next version, or to work with https://github.com/zeit/next.js/issues/8289, or to fix it on `@apollo/react-hooks` side?

**Comment by lfades** [comment]
@ceefour It's most likely an issue with Apollo not related to Next.js or this package.

**Comment by bradleykhan** [comment]
We're getting the same issue in our app, has there been any success at resolving the issue? I raised an issue in the `react-apollo` repo, no response yet though. [react-apollo/issues/3511](https://github.com/apollographql/react-apollo/issues/3511)

**Comment by ceefour** [comment]
`withApollo(..., {getDataFromTree: "ssr"})` seem to "hide" the warning? I don't know how it works (or not work) though..

**Comment by qw-in** [comment]
@ceefour `{getDataFromTree: "ssr"}` is working fine as it does not attempt to `getDataFromTree` in the browser

In `4.3.0` when using default settings or `{getDataFromTree: "always"}` the error you see is caused by the call to `getDataFromTree` failing and then reverting to "normal" loading behaviour

**Comment by dallen4** [comment]
While I don't use `next-with-apollo` directly as I'm implementing the apollo libs directly, I found this issue by way of [an issue on react's repo](https://github.com/facebook/react/issues/9249) and the `{getDataFromTree: "ssr"}` didn't work for me, but upgrading `next` itself to `^9.0.5` seemed to fix the issue.

My package versions are as follows:
```
        "@apollo/react-hooks": "^3.0.1",
        "@apollo/react-ssr": "^3.0.1",
        "apollo-boost": "^0.4.4",
        "apollo-link-context": "^1.0.19",
        "next": "^9.0.5",
```
