### ISSUE TITLE
Using an async function as the client to allow the use of apollo-cache-persist?

### ISSUE THREAD

**Issue by mtkcs** [lfades/next-with-apollo#87]
In order to use `apollo-cache-persist` we need to await for the `persitCache` function:

```javascript
export default withApollo(async ({ initialState, ctx, headers }) => {
  const cache = new InMemoryCache().restore(initialState || {});

  if (process.browser) {
    await persistCache({
      cache,
      storage: window.localStorage,
    });
  }

  return new ApolloClient({ 
    cache,
    // ...
  });
});
```
This throws an error: 
```
TypeError: Cannot read property 'extract' of undefined
    at /.../node_modules/next-with-apollo/lib/withApollo.js:147:61
```

Any ideas on how to get this working?

**Comment by lfades** [comment]
@mtkcs It's not possible in the browser, the apollo client is created before render, and React doesn't have async mode, one thing you could do is import `persistCache` inside `useEffect` and run the async method there, that's most likely the ideal solution.
