### ISSUE TITLE
apollo devtools not working in chrome

### ISSUE THREAD

**Issue by jmensch1** [lfades/next-with-apollo#90]
I'm trying out Next for the first time, and I've got a basic app working as expected. The only issue is that apollo devtools isn't working in chrome. The option doesn't even show up in the list of devtools (e.g. react, redux, etc.) in the chrome inspector. I tried adding `connectToDevTools: true` in the `ApolloClient` constructor, but that didn't do anything. Any ideas? Thanks much

**Comment by wesbos** [comment]
I don't think this is related to next-with-apollo. 

I can confirm it is working without adding any custom flags. You can check for `window.__APOLLO_DEVTOOLS_GLOBAL_HOOK__` to see if dev tools have been loaded onto the page or not. If not, then try re-installing the chrome extension.

This can be close and re-opened in apollo-dev-tools if needed
