### ISSUE TITLE
Cookies not send in getInitialProps

### ISSUE THREAD

**Issue by rwieruch** [lfades/next-with-apollo#96]
Hey @lfades 

Thank you so much for this project. Saved me (and I guess others) lots of time setting it up myself. For my project, I set up a custom authentication with a GraphQL server with cookies. With every client-side request, the cookie is send accordingly. But not in getInitialProps:

```
DashboardPage.getInitialProps = async ctx => {
  const { apolloClient } = ctx;
  const { session } = nextCookie(ctx);

  console.log(session);

  const { data } = await apolloClient.query({ query: GET_ME });

  return {};
};
```

Even though the session logging shows me the cookie, the cookie never makes it to the server. This is my Apollo Client creation:

```
import { ApolloClient } from 'apollo-client';
import { InMemoryCache } from 'apollo-cache-inmemory';
import { HttpLink } from 'apollo-link-http';
import withApollo from 'next-with-apollo';

const httpLink = new HttpLink({
  uri: `${process.env.BASE_URL}/api/graphql`,
  credentials: 'include',
});

export default withApollo(
  ({ ctx, headers, initialState }) =>
    new ApolloClient({
      link: httpLink,
      cache: new InMemoryCache().restore(initialState || {}),
    })
);
```

I hope there is anything to make it work for the first SSR request 🚀

**Comment by chemicalkosek** [comment]
Try ma answer [https://github.com/apollographql/apollo-client/issues/4190#issuecomment-573195984](https://github.com/apollographql/apollo-client/issues/4190#issuecomment-573195984)

**Comment by rwieruch** [comment]
Thanks @chemicalkosek Adjusting my Apollo Client instantiation didn't help.

I followed https://github.com/lfades/next-with-apollo/issues/88#issuecomment-568222698 and this fixed the issue for me. However, I am not sure whether I want to set this explicitly every time.
