### ISSUE TITLE
What is the difference between this and api-routes-apollo-server-and-client

### ISSUE THREAD

**Issue by ReTWi** [lfades/next-with-apollo#97]
I'm new to apollo and want to ask what is the difference between this package and official  [next.js/examples/api-routes-apollo-server-and-client](https://github.com/zeit/next.js/tree/canary/examples/api-routes-apollo-server-and-client). What should i use and what should i change to use new apollo 3.0 Beta?

**Comment by lfades** [comment]
@ReTWi The package should be able to work with apollo 3.0 beta now, I released a new version like an hour ago.

It's not very different from the example you just mentioned (I also helped on that one), this package is a wrapper to reduce the boilerplate of adding Apollo to your app, without messing with Apollo libs. The example includes the boilerplate + the Apollo Client integration.
