### ISSUE TITLE
apolloClient is not available in Page's getInitialProps when using withApollo in _app

### ISSUE THREAD

**Issue by hoangvvo** [lfades/next-with-apollo#99]
If `withApollo` is used in `_app` (no SSR, no getInitialProps), `ctx.apolloClient` will be undefined in Page components.

https://github.com/lfades/next-with-apollo/blob/master/src/withApollo.tsx#L63

It seems that when there is no `getInitialProps` in `_app`, we have no way to set `apolloClient` to Page component's `ctx`.

**Comment by lfades** [comment]
@hoangvvo You need a custom `getInitialProps` in `_app.js` to add the Apollo Client to the page's `getInitialProps`, you may want to add `withApollo` directly to the page instead.

**Comment by hoangvvo** [comment]
Thanks. That's what I thought. I think the documentation should be updated to mention it.

**Comment by wesbos** [comment]
It is in the read me :) 

https://github.com/lfades/next-with-apollo#using-getinitialprops 

This can be closed

**Comment by hoangvvo** [comment]
@wesbos 
I'm referring to this section https://github.com/lfades/next-with-apollo#using-_app

> If you want to add Apollo to all pages, you can use pages/_app.js, like so:

The code snippet below does not mention having `App.getInitialProps`. This may be misleading.
